services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_new
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    dns:
      - 8.8.8.8
      - 8.8.4.4
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  

volumes:
  ollama:
